GET http://localhost:3000/api/user/admin
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6IkFkbWluaXN0cmFkb3IxMiIsImlhdCI6MTYzNjQ2NzIzMiwiZXhwIjoxNjM2NDY4MTMyfQ.xejNzli1WgHlx6a3MqayMtX6WqUhndmdeZFB-5YieNM



###

POST https://arquitectura2-api.herokuapp.com/products
Content-Type: application/json

{
    "name": "Fer",
    "price": "2",
    "stock": "66",
    "available": true
}

###

POST https://carrito-jwt.herokuapp.com/api/user/register
Content-Type: application/json

{
    "nickname": "Administrador12",
    "email": "administrator9@gmail.com",
    "password": "1234521219"
}

###

POST https://carrito-jwt.herokuapp.com/api/user/users/login
Content-Type: application/json

{
    "nickname" : "Administrador8",
    "password": "1234521219"
}

###
POST http://localhost:3000/api/user/users/login
Content-Type: application/json

{
    "nickname" : "Administrador12",
    "password": "1234521219"
}